
name: 'recharge_source'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

vars:
  recharge_source:
    address: "{{ source('recharge','address') }}"
    address_shipping_line: "{{ source('recharge','address_shipping_line') }}"
    charge: "{{ source('recharge','charge') }}"
    charge_discount_code: "{{ source('recharge','charge_discount_code') }}"
    charge_line_item: "{{ source('recharge','charge_line_item') }}"
    charge_note_attribute: "{{ source('recharge','charge_note_attribute') }}"
    charge_shipping_line: "{{ source('recharge','charge_shipping_line') }}"
    customer: "{{ source('recharge','customer') }}"
    discount: "{{ source('recharge','discount') }}"
    one_time_product: "{{ source('recharge','one_time_product') }}"
    order: "{{ source('recharge','order') }}"
    order_line_item: "{{ source('recharge','order_line_item') }}"
    payment_method: "{{ source('recharge','payment_method') }}"
    plan: "{{ source('recharge','plan') }}"
    subscription: "{{ source('recharge','subscription') }}"
    subscription_history: "{{ source('recharge','subscription_history') }}"
    recharge__address_passthrough_columns: [] 
    recharge__charge_passthrough_columns: [] 
    recharge__charge_line_item_passthrough_columns: [] 
    recharge__order_passthrough_columns: [] 
    recharge__order_line_passthrough_columns: [] 
    recharge__plan_passthrough_columns: [] 
    recharge__subscription_passthrough_columns: [] 
    recharge__subscription_history_passthrough_columns: []

models:
  recharge_source:
    tmp:
      materialized: view
    +materialized: table
    +schema: recharge_source