
{% macro get_charge_columns() %}

{% set columns = [
    {"name": "id", "datatype": dbt_utils.type_int()},
    {"name": "address_id", "datatype": dbt_utils.type_int()},
    {"name": "customer_id", "datatype": dbt_utils.type_int()},
    {"name": "first_name", "datatype": dbt_utils.type_string()},
    {"name": "last_name", "datatype": dbt_utils.type_string()},
    {"name": "customer_hash", "datatype": dbt_utils.type_string()},
    {"name": "note", "datatype": dbt_utils.type_string()},
    {"name": "created_at", "datatype": dbt_utils.type_timestamp()},
    {"name": "updated_at", "datatype": dbt_utils.type_timestamp()},
    {"name": "processed_at", "datatype": dbt_utils.type_timestamp()},
    {"name": "scheduled_at", "datatype": dbt_utils.type_timestamp()},
    {"name": "shipments_count", "datatype": dbt_utils.type_int()},
    {"name": "shopify_order_id", "datatype": dbt_utils.type_int()},
    {"name": "sub_total", "datatype": dbt_utils.type_int()},
    {"name": "subtotal_price", "datatype": dbt_utils.type_float()},
    {"name": "tags", "datatype": dbt_utils.type_string()},
    {"name": "tax_lines", "datatype": dbt_utils.type_float()},
    {"name": "total_discounts", "datatype": dbt_utils.type_float()},
    {"name": "total_line_items_price", "datatype": dbt_utils.type_float()},
    {"name": "total_price", "datatype": dbt_utils.type_float()},
    {"name": "total_tax", "datatype": dbt_utils.type_float()},
    {"name": "total_weight", "datatype": dbt_utils.type_float()},
    {"name": "type", "datatype": dbt_utils.type_string()},
    {"name": "status", "datatype": dbt_utils.type_string()},
    {"name": "total_refunds", "datatype": dbt_utils.type_float()},
    {"name": "transaction_id", "datatype": dbt_utils.type_string()},
    {"name": "email", "datatype": dbt_utils.type_string()},
    {"name": "processor_name", "datatype": dbt_utils.type_string()},
    {"name": "has_uncommitted_changes", "datatype": "boolean"},
    {"name": "last_charge_attempt_date", "datatype": dbt_utils.type_timestamp()},
    {"name": "retry_date", "datatype": dbt_utils.type_timestamp()},
    {"name": "error_type", "datatype": dbt_utils.type_string()},
    {"name": "error", "datatype": dbt_utils.type_string()},
    {"name": "number_times_tried", "datatype": dbt_utils.type_int()},
    {"name": "shopify_variant_id_not_found", "datatype": dbt_utils.type_string()},
    {"name": "billing_address_first_name", "datatype": dbt_utils.type_string()},
    {"name": "billing_address_last_name", "datatype": dbt_utils.type_string()},
    {"name": "billing_address_address_1", "datatype": dbt_utils.type_string()},
    {"name": "billing_address_address_2", "datatype": dbt_utils.type_string()},
    {"name": "billing_address_city", "datatype": dbt_utils.type_string()},
    {"name": "billing_address_province", "datatype": dbt_utils.type_string()},
    {"name": "billing_address_country", "datatype": dbt_utils.type_string()},
    {"name": "billing_address_zip", "datatype": dbt_utils.type_string()},
    {"name": "billing_address_company", "datatype": dbt_utils.type_string()},
    {"name": "billing_address_phone", "datatype": dbt_utils.type_string()},
    {"name": "shipping_address_first_name", "datatype": dbt_utils.type_string()},
    {"name": "shipping_address_last_name", "datatype": dbt_utils.type_string()},
    {"name": "shipping_address_address_1", "datatype": dbt_utils.type_string()},
    {"name": "shipping_address_address_2", "datatype": dbt_utils.type_string()},
    {"name": "shipping_address_city", "datatype": dbt_utils.type_string()},
    {"name": "shipping_address_province", "datatype": dbt_utils.type_string()},
    {"name": "shipping_address_country", "datatype": dbt_utils.type_string()},
    {"name": "shipping_address_zip", "datatype": dbt_utils.type_string()},
    {"name": "shipping_address_company", "datatype": dbt_utils.type_string()},
    {"name": "shipping_address_phone", "datatype": dbt_utils.type_string()},
    {"name": "client_details_browser_ip", "datatype": dbt_utils.type_string()},
    {"name": "client_details_user_agent", "datatype": dbt_utils.type_string()},
    {"name": "_fivetran_synced", "datatype": dbt_utils.type_timestamp()}
] %}

{{ return(columns) }}

{% endmacro %}